# Generated by Django 6.1.1 on 2026-09-20 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='orders.suborder'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['customer', 'status'], name='service_boo_custome_6c84ca_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['store', 'status'], name='service_boo_store_i_23c053_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['scheduled_at'], name='service_boo_schedul_cf9905_idx'),
        ),
    ]
