# Generated by Django 6.1.1 on 2026-10-07 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0002_quickorder'),
        ('stores', '0002_seed_regions_and_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('sourcing', 'Sourcing from store'), ('picked_up', 'Picked up / On the way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='StorePurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=30, unique=True)),
                ('listing_title_snapshot', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price the platform pays the store per unit', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent to store'), ('accepted', 'Accepted by store'), ('ready', 'Ready for pickup'), ('picked_up', 'Picked up'), ('rejected', 'Rejected by store'), ('cancelled', 'Cancelled')], default='sent', max_length=20)),
                ('vendor_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note - not visible to the vendor')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(help_text='Internal link - never exposed to the vendor', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='orders.quickorder')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.listing')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stores.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'store purchase order',
                'verbose_name_plural': 'store purchase orders',
                'db_table': 'store_purchase_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='store_purch_store_i_0b0773_idx'), models.Index(fields=['customer_order'], name='store_purch_custome_5e42da_idx')],
            },
        ),
    ]
