# Generated by Django 6.1.1 on 2026-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_store_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepurchaseorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepurchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid (confirmed by store)')], default='unpaid', help_text='The store confirms it has been paid before the goods can be picked up', max_length=10),
        ),
    ]
