# Generated by Django 6.1.1 on 2026-10-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_purchase_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepurchaseorder',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the store says it received when marking the order as paid', max_digits=12, null=True),
        ),
    ]
