# Generated by Django 6.1.1 on 2026-10-07 08:55

from django.db import migrations, models


def mark_accepted_orders_agreed(apps, schema_editor):
    """Orders the store already accepted (or later) have an agreed price."""
    StorePurchaseOrder = apps.get_model('orders', 'StorePurchaseOrder')
    StorePurchaseOrder.objects.filter(
        status__in=['accepted', 'ready', 'picked_up']
    ).update(price_status='agreed')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchase_order_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='storepurchaseorder',
            name='price_status',
            field=models.CharField(choices=[('offered', 'Offered by Mo Expressway - store to accept'), ('awaiting_quote', 'Waiting for the store to quote'), ('vendor_proposed', 'Store proposed a price - admin to respond'), ('agreed', 'Agreed')], default='offered', max_length=20),
        ),
        migrations.AddField(
            model_name='storepurchaseorder',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storepurchaseorder',
            name='vendor_quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price the store proposed for this order', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storepurchaseorder',
            name='vendor_quote_note',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(mark_accepted_orders_agreed, migrations.RunPython.noop),
    ]
