# Generated by Django 6.1.1 on 2026-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_purchase_order_price_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exactly what the customer paid, recorded when the order is closed', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('sourcing', 'Sourcing from store'), ('picked_up', 'Picked up / On the way'), ('delivered', 'Delivered'), ('closed', 'Closed (payment recorded)'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
