# Generated by Django 6.1.1 on 2026-09-20 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to='orders.suborder'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['suborder'], name='delivery_as_suborde_dc2619_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['delivery_agent', 'status'], name='delivery_as_deliver_8eed53_idx'),
        ),
    ]
