# Generated by Django 6.1.1 on 2026-09-20 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('commissions', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionledger',
            name='suborder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_ledger', to='orders.suborder'),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commission_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commission_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='stores.store'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commission_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='stores.store'),
        ),
        migrations.AddField(
            model_name='payout',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='settled_in_payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='commissions.payout'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['scope_type', 'is_active'], name='commission__scope_t_a364d2_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['store'], name='commission__store_i_96bfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['category'], name='commission__categor_a91be7_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['store', '-created_at'], name='payouts_store_i_b31623_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payouts_status_20cd29_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['store', 'status'], name='commission__store_i_57dedd_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionledger',
            index=models.Index(fields=['suborder'], name='commission__suborde_20cf46_idx'),
        ),
    ]
