# Generated by Django 6.1.1 on 2026-09-21 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_seed_regions_and_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField(help_text='First day of the billed month (e.g. 2026-09-01)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscription_invoices', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_subscription_invoices', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invoices', to='stores.store')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subscription_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription invoice',
                'verbose_name_plural': 'subscription invoices',
                'db_table': 'subscription_invoices',
                'ordering': ['-period_month'],
                'indexes': [models.Index(fields=['period_month', 'status'], name='subscriptio_period__e88624_idx'), models.Index(fields=['store', '-period_month'], name='subscriptio_store_i_235398_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'period_month'), name='uq_subscription_store_month')],
            },
        ),
    ]
