# Generated by Django 6.1.1 on 2026-09-20 11:41

from django.db import migrations


GOODS_SUBCATEGORIES = [
    "Electronics",
    "Fashion",
    "Home & Living",
    "Beauty & Health",
    "Groceries",
    "Automotive",
    "Sports & Outdoors",
    "Books & Stationery",
    "Services",
]

SERVICES_SUBCATEGORIES = [
    "Electronics Repair",
    "Home Repair & Maintenance",
    "Vehicle Services",
    "Beauty & Spa",
    "Professional Services",
    "Cleaning",
    "Delivery & Logistics",
    "Catering & Food",
    "Photography",
]


def seed(apps, schema_editor):
    Region = apps.get_model("stores", "Region")
    StoreCategory = apps.get_model("stores", "StoreCategory")
    for name in ["Dar es Salaam", "Arusha", "Mwanza", "Dodoma"]:
        Region.objects.get_or_create(name=name)

    goods, _ = StoreCategory.objects.get_or_create(name="Goods", parent=None)
    services, _ = StoreCategory.objects.get_or_create(name="Services", parent=None)
    for name in GOODS_SUBCATEGORIES:
        StoreCategory.objects.get_or_create(name=name, parent=goods)
    for name in SERVICES_SUBCATEGORIES:
        StoreCategory.objects.get_or_create(name=name, parent=services)


def unseed(apps, schema_editor):
    StoreCategory = apps.get_model("stores", "StoreCategory")
    StoreCategory.objects.exclude(created_by__isnull=False).delete()
    Region = apps.get_model("stores", "Region")
    Region.objects.exclude(created_by__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]