# Generated by Django 6.1.1 on 2026-10-07 07:22

from django.db import migrations, models


def stores_with_invoices_to_monthly(apps, schema_editor):
    """Stores that were already being billed keep paying: put them on the
    monthly plan with their most recent invoice amount as the fee."""
    Store = apps.get_model('stores', 'Store')
    SubscriptionInvoice = apps.get_model('subscriptions', 'SubscriptionInvoice')
    for store in Store.objects.all():
        last = (
            SubscriptionInvoice.objects.filter(store_id=store.pk)
            .order_by('-period_month')
            .first()
        )
        if last is not None:
            store.subscription_plan = 'monthly'
            store.monthly_fee = last.amount
            store.save(update_fields=['subscription_plan', 'monthly_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_seed_regions_and_categories'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee billed each month on the monthly plan', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='plan_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly')], default='free', help_text='Free stores are never billed; monthly stores get a monthly invoice', max_length=10),
        ),
        migrations.RunPython(stores_with_invoices_to_monthly, migrations.RunPython.noop),
    ]
